# Generated by Django 4.2.29 on 2026-03-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqi_tracker', '0002_station_and_fk'),
    ]

    operations = [
        # Sprint 1 put unique=True on station_time (one station, so safe).
        # Sprint 2 added unique_together=(station, station_time) but didn't
        # remove this, causing UNIQUE constraint failures when multiple stations
        # have readings at the same timestamp (e.g. all daily CSVs at midnight UTC).
        migrations.AlterField(
            model_name="aqireading",
            name="station_time",
            field=__import__("django.db.models", fromlist=["DateTimeField"]).DateTimeField(),
        ),
    ]
